spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create
  cloud:
      inetutils:
        preferred-networks:
          - 192.168
          - 10.0
server:
  port: 6004
  context-path: /user
management:
  context-path: /admin
  port: 6005
api.version: v1


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: false
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    hostname: user
