spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 6002
  context-path: /product
management:
  context-path: /admin
  port: 6003

api.version: v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: false
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
