spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 6000
  context-path: /order
management:
  context-path: /admin
  port: 6001

api.version: v1

user:
  context-path: /user
  version: v1
product:
  context-path: /product
  version: v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health

feign:
  hystrix:
    enabled: true

