spring:
  profiles:
    active: local
  cloud:
      inetutils:
        preferred-networks:
          - 192.168
          - 10.0

server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false